/*$file${.::MiniSumo2.ino} #################################################*/
/*
* Model: MiniSumo2.qm
* File:  ${.::MiniSumo2.ino}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::MiniSumo2.ino} ##############################################*/
#define Q_PARAM_SIZE 4 // 32 bit parameters (e.g. pointers) passed between events.

#include "qpn.h"     // QP-nano framework
#include "Arduino.h" // Arduino API

#include "Zumo32U4.h"

static int DISABLE_PRINT = 0; // false

#define PRINT_IF_ENABLED if (!DISABLE_PRINT)
#define ALWAYS_PRINT if (1==1)
#define DO_NOT_PRINT if (1==0)

static int started = 0;

//============================================================================
// declare all AO classes...
/*$declare${AOs::LineEvtSimulator} #########################################*/
/*${AOs::LineEvtSimulator} .................................................*/
typedef struct LineEvtSimulator {
/* protected: */
    QActive super;

/* public: */
    const uint8_t period = 20;
    const uint16_t line_sensor_threshold = 1000;
    enum { BOUNDARY_ON_LEFT, BOUNDARY_ON_RIGHT, BOUNDARY_IN_FRONT } boundary_position;
} LineEvtSimulator;

/* public: */
static void LineEvtSimulator_printToLCD(LineEvtSimulator * const me, uint16_t * lineSensorValues);
static void LineEvtSimulator_printBar(LineEvtSimulator * const me, uint8_t height);

/* protected: */
static QState LineEvtSimulator_initial(LineEvtSimulator * const me);
static QState LineEvtSimulator_running(LineEvtSimulator * const me);
/*$enddecl${AOs::LineEvtSimulator} #########################################*/
/*$declare${AOs::Sumo} #####################################################*/
/*${AOs::Sumo} .............................................................*/
typedef struct Sumo {
/* protected: */
    QActive super;

/* public: */
    uint16_t ready_time_remaining = 0;
    const uint16_t turn_speed = 250;
    const uint16_t ready_timeout_ms = 5000;
    enum  { LAST_TURN_WAS_LEFT, LAST_TURN_WAS_RIGHT};
    int last_turn;
    const uint8_t scan_timeout = 2000;
    int last_boundary_position = LineEvtSimulator::BOUNDARY_ON_LEFT;
    const uint8_t safety_timeout = 30000;
    bool debug_mode = true;
} Sumo;

/* protected: */
static QState Sumo_initial(Sumo * const me);
static QState Sumo_paused(Sumo * const me);
static QState Sumo_ready(Sumo * const me);
static QState Sumo_scanning(Sumo * const me);
static QState Sumo_turn_right(Sumo * const me);
static QState Sumo_unused(Sumo * const me);
static QState Sumo_turn_left(Sumo * const me);
static QState Sumo_driving(Sumo * const me);
static QState Sumo_reverse(Sumo * const me);
/*$enddecl${AOs::Sumo} #####################################################*/
/*$declare${AOs::ButtonEvtSimulator} #######################################*/
/*${AOs::ButtonEvtSimulator} ...............................................*/
typedef struct ButtonEvtSimulator {
/* protected: */
    QActive super;

/* public: */
    const uint8_t period =50;
} ButtonEvtSimulator;

/* protected: */
static QState ButtonEvtSimulator_initial(ButtonEvtSimulator * const me);
static QState ButtonEvtSimulator_running(ButtonEvtSimulator * const me);
/*$enddecl${AOs::ButtonEvtSimulator} #######################################*/
/*$declare${AOs::ProximityEvtSimulator} ####################################*/
/*${AOs::ProximityEvtSimulator} ............................................*/
typedef struct ProximityEvtSimulator {
/* protected: */
    QActive super;

/* public: */
    const uint8_t period = 50;
} ProximityEvtSimulator;

/* public: */
static uint8_t ProximityEvtSimulator_getConfidence(uint8_t highValue, uint8_t lowValue);

/* protected: */
static QState ProximityEvtSimulator_initial(ProximityEvtSimulator * const me);
static QState ProximityEvtSimulator_running(ProximityEvtSimulator * const me);
/*$enddecl${AOs::ProximityEvtSimulator} ####################################*/
//...

// AO instances and event queue buffers for them...
Sumo AO_Sumo;
ButtonEvtSimulator AO_ButtonSim;
ProximityEvtSimulator AO_ProximitySim;
LineEvtSimulator AO_LineSim;


// Other objects
Zumo32U4LCD lcd;
Zumo32U4ButtonA buttonA;
Zumo32U4Motors motors;
Zumo32U4LineSensors lineSensors;
Zumo32U4ProximitySensors proxSensors;


static QEvt l_SumoQSto[10]; // Event queue storage for Blinky
static QEvt l_ButtonSimQSto[10];
static QEvt l_ProxSimQSto[10];
static QEvt l_LineSimQSto[10];

//...

//============================================================================
// QF_active[] array defines all active object control blocks ----------------
QActiveCB const Q_ROM QF_active[] = {
    { (QActive *)0,               (QEvt *)0,           0U                        },
    { (QActive *)&AO_Sumo,        l_SumoQSto,          Q_DIM(l_SumoQSto)         },
    { (QActive *)&AO_ButtonSim,   l_ButtonSimQSto,     Q_DIM(l_ButtonSimQSto)    },
    { (QActive *)&AO_ProximitySim,l_ProxSimQSto,       Q_DIM(l_ProxSimQSto)      },
    { (QActive *)&AO_LineSim,     l_LineSimQSto,       Q_DIM(l_LineSimQSto)      }
};

//============================================================================
// various constants for the application...
enum {
    BSP_TICKS_PER_SEC = 1000, // number of system clock ticks in one second
};

enum Signals {
 BUTTON_PRESS_SIG = Q_USER_SIG,
 READY_TIMEOUT_SIG,
 OPPONENT_ON_RIGHT_SIG,
 OPPONENT_ON_LEFT_SIG,
 OPPONENT_IN_FRONT_SIG,
 IN_RING_SIG,
 ON_BOUNDARY_SIG,
 MAXSIGS
};



//............................................................................
void setup() {
    // initialize the QF-nano framework
    QF_init(Q_DIM(QF_active));

    // initialize all AOs...
    QActive_ctor(&AO_Sumo.super,         Q_STATE_CAST(&Sumo_initial));

    QActive_ctor(&AO_ButtonSim.super,    Q_STATE_CAST(&ButtonEvtSimulator_initial));

    QActive_ctor(&AO_ProximitySim.super, Q_STATE_CAST(&ProximityEvtSimulator_initial));

    QActive_ctor(&AO_LineSim.super,      Q_STATE_CAST(&LineEvtSimulator_initial));
}

//............................................................................
void loop() {
    QF_run(); // run the QF-nano framework
}

//============================================================================
// interrupts...
ISR(TIMER4_COMPA_vect) {
    QF_tickXISR(0); // process time events for tick rate 0
}

//============================================================================
// QF callbacks...
void QF_onStartup(void) {

    /**
        1. Generally, ignoring TC4H when writing TCNT, OCR and other registers
           (i.e. we assume it is zero) in each case as we expect the count to fit in 8 bits.
        2. General idea is to use OCR4A to generate an interrupt. We could also use the overflow interrupt, but a
           handler for that is defined in the pololu library code, so compilation will fail or we will need to
           remove the handler from the pololu code.
        3. See below for specifics about interaction between OCR4A and OCR4C.
    */

    // TCCR4A is used to generate output pin signals (along with interrupt), but we don't want to generate output.
    TCCR4A = 0;
    // Prescale by 1/128
    TCCR4B = (0<<PWM4X) | (0<<PSR4) | (0<<DTPS41) | (0<<DTPS40) | (1<<CS43) | (0<<CS42) | (0<<CS41) | (0<<CS40);

    // For some reason, not setting TCCR4D to zero explicitly results in doubling the time interval. All initial
    // values of TCCR4D are zero according to the datasheet. Since I was unable to explain this, I have expliclty
    // set all control registers to zero instead of assuming they are zero.
    TCCR4C = 0;
    TCCR4D = 0;
    TCCR4E = 0;

    TCNT4=0x00;

    /* Calculate Timer Count Max.
        1. We don't explicilty set OCR4B/D as it is not used. Setting it has no effect (verified).
        2. We set OCR4C to the same value as OCR4A. OCR4A generates an interrupt on compare match.
           OCR4C contains the 'TOP' value,  i.e. the value to which the timer is reset.
        2.1 Note: Not setting OCR4C causes the uP to double the count. No idea why. (verified)
        2.2 Note: Setting OCR4C to zero or Setting it to a value other than OCR4A, results in no OCR4A interrupt being generated. (verified)
    */
    OCR4A  = (F_CPU / BSP_TICKS_PER_SEC / 128U) - 1;
    OCR4C =(F_CPU / BSP_TICKS_PER_SEC / 128U) - 1U;

    // Enable TIMER compare Interrupt for OCR4A
    TIMSK4= (1<<OCIE4A);
}
//............................................................................
void QV_onIdle(void) {   // called with interrupts DISABLED
    // Put the CPU and peripherals to the low-power mode. You might
    // need to customize the clock management for your application,
    // see the datasheet for your particular AVR MCU.
    SMCR = (0 << SM0) | (1 << SE); // idle mode, adjust to your project
    QV_CPU_SLEEP();  // atomically go to sleep and enable interrupts
}
//............................................................................
void Q_onAssert(char const Q_ROM * const file, int line) {
    // implement the error-handling policy for your application!!!
    QF_INT_DISABLE(); // disable all interrupts
    QF_RESET();  // reset the CPU
}

//============================================================================
// define all AO classes (state machine)...
/*$define${AOs::Sumo} ######################################################*/
/* Check for the minimum required QP version */
#if ((QP_VERSION < 601) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 6.0.1 or higher required
#endif
/*${AOs::Sumo} .............................................................*/
/*${AOs::Sumo::SM} .........................................................*/
static QState Sumo_initial(Sumo * const me) {
    /*${AOs::Sumo::SM::initial} */
    return Q_TRAN(&Sumo_paused);
}
/*${AOs::Sumo::SM::paused} .................................................*/
static QState Sumo_paused(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::paused} */
        case Q_ENTRY_SIG: {
            ledRed(HIGH);

            PRINT_IF_ENABLED {
                lcd.clear();
                lcd.print(F("Press A:"));


                lcd.gotoXY(0, 1);
                lcd.print(readBatteryMillivolts());
                lcd.print(":");
                if(started == 0) {
                    lcd.print("rst");
                    started = 1;
                } else {
                    lcd.print("ret");
                }
            }
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sumo::SM::paused::BUTTON_PRESS} */
        case BUTTON_PRESS_SIG: {
            ledRed(LOW);
            me->ready_time_remaining = me->ready_timeout_ms;
            QActive_armX((QActive *)me, 0 /*Tick rate */, 10 /* millis */, 10);

            // Toggle speed (used for debugging)
            //if (me->debug_mode) {
            //    if (me->turn_speed == 0) {
            //        me->turn_speed = 250;
            //    } else {
            //        me->turn_speed = 0;
            //    }
            //}
            status_ = Q_TRAN(&Sumo_ready);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Sumo::SM::ready} ..................................................*/
static QState Sumo_ready(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::ready::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            me->ready_time_remaining -= 10; // reduce by 10 millis.
            float timeToPrint = ((float)me->ready_time_remaining)/1000;
            lcd.clear();
            lcd.print(timeToPrint, 2);
            if(me->ready_time_remaining <= 0){
                QActive_disarmX((QActive *)me, 0 /*Tick rate */);
                QACTIVE_POST((QActive *)me, READY_TIMEOUT_SIG, 0);
            }
            status_ = Q_TRAN(&Sumo_ready);
            break;
        }
        /*${AOs::Sumo::SM::ready::READY_TIMEOUT} */
        case READY_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Sumo_scanning);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Sumo::SM::scanning} ...............................................*/
static QState Sumo_scanning(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::scanning} */
        case Q_ENTRY_SIG: {
            QActive_armX((QActive *)me, 0 /*Tick rate */, me->scan_timeout/* millis */, 0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sumo::SM::scanning} */
        case Q_EXIT_SIG: {
            QActive_disarmX((QActive *)me, 0);
            motors.setSpeeds(0,0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sumo::SM::scanning::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Sumo_turn_left);
            break;
        }
        /*${AOs::Sumo::SM::scanning::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Sumo_driving);
            break;
        }
        /*${AOs::Sumo::SM::scanning::OPPONENT_IN_FRONT} */
        case OPPONENT_IN_FRONT_SIG: {
            status_ = Q_TRAN(&Sumo_driving);
            break;
        }
        /*${AOs::Sumo::SM::scanning::BUTTON_PRESS} */
        case BUTTON_PRESS_SIG: {
            status_ = Q_TRAN(&Sumo_paused);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Sumo::SM::scanning::turn_right} ...................................*/
static QState Sumo_turn_right(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::scanning::turn_right} */
        case Q_ENTRY_SIG: {
            PRINT_IF_ENABLED {
                lcd.clear();
                lcd.print("SRight");
            }

            motors.setSpeeds(me->turn_speed, -me->turn_speed);
            me->last_turn = me->LAST_TURN_WAS_RIGHT;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Sumo_scanning);
            break;
        }
    }
    return status_;
}
/*${AOs::Sumo::SM::scanning::unused} .......................................*/
static QState Sumo_unused(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::scanning::unused} */
        case Q_ENTRY_SIG: {
            if (me->last_boundary_position == LineEvtSimulator::BOUNDARY_ON_LEFT) {
                status_ = Q_TRAN(&Sumo_turn_right);
            } else {
                status_ = Q_TRAN(&Sumo_turn_left);
            }

            DO_NOT_PRINT {
                lcd.clear();
                lcd.print("LBP:"); lcd.print(me->last_boundary_position);
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Sumo_scanning);
            break;
        }
    }
    return status_;
}
/*${AOs::Sumo::SM::scanning::turn_left} ....................................*/
static QState Sumo_turn_left(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::scanning::turn_left} */
        case Q_ENTRY_SIG: {
            PRINT_IF_ENABLED {
                lcd.clear();
                lcd.print("SLeft");
            }

            motors.setSpeeds(-me->turn_speed, me->turn_speed);
            me->last_turn = me->LAST_TURN_WAS_LEFT;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Sumo_scanning);
            break;
        }
    }
    return status_;
}
/*${AOs::Sumo::SM::driving} ................................................*/
static QState Sumo_driving(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::driving} */
        case Q_ENTRY_SIG: {
            //QActive_armX((QActive *)me, 0 /*Tick rate */, me->safety_timeout/* millis */, 0);

            uint8_t confidence = Q_PAR(me);

            int speed = me->turn_speed;
            // confidence > 50% we want to move faster than normal.
            if (confidence > 50) {
                speed = (2 * ((float)confidence)/100) * me->turn_speed;
            }

            motors.setSpeeds(speed, speed);

            PRINT_IF_ENABLED {
                lcd.clear();
                lcd.print("Drive");
                lcd.gotoXY(0,1);
                lcd.print("Sp:");
                lcd.print(speed);
            }

            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sumo::SM::driving} */
        case Q_EXIT_SIG: {
            //QActive_disarmX((QActive *)me, 0);
            motors.setSpeeds(0,0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sumo::SM::driving::OPPONENT_ON_LEFT} */
        case OPPONENT_ON_LEFT_SIG: {
            status_ = Q_TRAN(&Sumo_turn_left);
            break;
        }
        /*${AOs::Sumo::SM::driving::OPPONENT_ON_RIGHT} */
        case OPPONENT_ON_RIGHT_SIG: {
            status_ = Q_TRAN(&Sumo_turn_right);
            break;
        }
        /*${AOs::Sumo::SM::driving::ON_BOUNDARY} */
        case ON_BOUNDARY_SIG: {
            // Transfer information about boundary location to state machine variable.
            me->last_boundary_position = Q_PAR(me);
            status_ = Q_TRAN(&Sumo_reverse);
            break;
        }
        /*${AOs::Sumo::SM::driving::BUTTON_PRESS} */
        case BUTTON_PRESS_SIG: {
            status_ = Q_TRAN(&Sumo_paused);
            break;
        }
        /*${AOs::Sumo::SM::driving::OPPONENT_IN_FRONT} */
        case OPPONENT_IN_FRONT_SIG: {
            status_ = Q_TRAN(&Sumo_driving);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Sumo::SM::reverse} ................................................*/
static QState Sumo_reverse(Sumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Sumo::SM::reverse} */
        case Q_ENTRY_SIG: {
            //int reverse_timeout = 150 * 300 /(me->turn_speed);
            int reverse_timeout = 500;
            QActive_armX((QActive *)me, 0 /*Tick rate */, reverse_timeout/* millis */, 0);

            PRINT_IF_ENABLED {
                lcd.clear();
                lcd.print("reverse");
            }

            motors.setSpeeds(-me->turn_speed, -me->turn_speed);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sumo::SM::reverse} */
        case Q_EXIT_SIG: {
            QActive_disarmX((QActive *)me, 0);
            motors.setSpeeds(0,0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Sumo::SM::reverse::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            DO_NOT_PRINT {
                lcd.clear();
                lcd.print("LBP:"); lcd.print(me->last_boundary_position);
            }
            /*${AOs::Sumo::SM::reverse::Q_TIMEOUT::[boundarynotonleft]} */
            if (me->last_boundary_position != LineEvtSimulator::BOUNDARY_ON_LEFT) {
                status_ = Q_TRAN(&Sumo_turn_left);
            }
            /*${AOs::Sumo::SM::reverse::Q_TIMEOUT::[boundaryonleft]} */
            else if (me->last_boundary_position == LineEvtSimulator::BOUNDARY_ON_LEFT) {
                status_ = Q_TRAN(&Sumo_turn_right);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        /*${AOs::Sumo::SM::reverse::OPPONENT_IN_FRONT} */
        case OPPONENT_IN_FRONT_SIG: {
            status_ = Q_TRAN(&Sumo_driving);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Sumo} ######################################################*/
/*$define${AOs::ButtonEvtSimulator} ########################################*/
/*${AOs::ButtonEvtSimulator} ...............................................*/
/*${AOs::ButtonEvtSimulat~::SM} ............................................*/
static QState ButtonEvtSimulator_initial(ButtonEvtSimulator * const me) {
    /*${AOs::ButtonEvtSimulat~::SM::initial} */
    QActive_armX(&me->super, 0 /*Tick rate */, me->period /* millis */, me->period);
    return Q_TRAN(&ButtonEvtSimulator_running);
}
/*${AOs::ButtonEvtSimulat~::SM::running} ...................................*/
static QState ButtonEvtSimulator_running(ButtonEvtSimulator * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::ButtonEvtSimulat~::SM::running::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            //lcd.clear();
            //lcd.print(F("Timer"));

            if (buttonA.getSingleDebouncedPress()) {
                QACTIVE_POST_X((QActive *)&AO_Sumo, 1, BUTTON_PRESS_SIG, 0);
            }
            status_ = Q_TRAN(&ButtonEvtSimulator_running);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::ButtonEvtSimulator} ########################################*/
/*$define${AOs::ProximityEvtSimulator} #####################################*/
/*${AOs::ProximityEvtSimulator} ............................................*/
/*${AOs::ProximityEvtSimu~::getConfidence} .................................*/
static uint8_t ProximityEvtSimulator_getConfidence(uint8_t highValue, uint8_t lowValue) {
    float diff = (float)(highValue - lowValue);
    return 100 * diff/proxSensors.getNumBrightnessLevels();
}

/*${AOs::ProximityEvtSimu~::SM} ............................................*/
static QState ProximityEvtSimulator_initial(ProximityEvtSimulator * const me) {
    /*${AOs::ProximityEvtSimu~::SM::initial} */
    proxSensors.initThreeSensors();
    QActive_armX(&me->super, 0 /*Tick rate */, me->period /* millis */, me->period);
    return Q_TRAN(&ProximityEvtSimulator_running);
}
/*${AOs::ProximityEvtSimu~::SM::running} ...................................*/
static QState ProximityEvtSimulator_running(ProximityEvtSimulator * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::ProximityEvtSimu~::SM::running::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            proxSensors.read();
            uint8_t frontLeftCount = proxSensors.countsFrontWithLeftLeds();
            uint8_t frontRightCount = proxSensors.countsFrontWithRightLeds();
            uint8_t leftCount = proxSensors.countsLeftWithLeftLeds();
            uint8_t rightCount = proxSensors.countsRightWithRightLeds();
            DO_NOT_PRINT { // Use ALWAYS_PRINT to print
                lcd.clear();
                lcd.print("L:");
                lcd.print(leftCount);
                lcd.print("FL:");
                lcd.print(frontLeftCount);
                lcd.gotoXY(0, 1);
                lcd.print("R:");
                lcd.print(rightCount);
                lcd.print("FR:");
                lcd.print(frontRightCount);
            }
            if(leftCount >= 2) {
              QACTIVE_POST_X((QActive *)&AO_Sumo, 1, OPPONENT_ON_LEFT_SIG, 100);
              //lcd.clear();
              //lcd.print("GoLft");
            } else if (rightCount >= 2) {
              QACTIVE_POST_X((QActive *)&AO_Sumo, 1, OPPONENT_ON_RIGHT_SIG, 100);
              //lcd.clear();
              //lcd.print("GoRgt");
            }
            if (frontLeftCount >= 5 || frontRightCount  >= 5) {

              // 6 is 100% confidence based on experimental results for a 32" sumo mat with robot in center
              // and opponent straight in front on boundary.
              int confidence = 100 * ((float)(frontLeftCount + frontRightCount))/6;
              QACTIVE_POST_X((QActive *)&AO_Sumo, 1,  OPPONENT_IN_FRONT_SIG, confidence);

            }
            /*
            else if (rightCount <= 3) {
              QACTIVE_POST((QActive *)&AO_Sumo, OPPONENT_ON_RIGHT_SIG, 0);
            } else {
              uint8_t confidence = ProximityEvtSimulator_getConfidence(rightCount, 0);
              QACTIVE_POST((QActive *)&AO_Sumo, OPPONENT_IN_FRONT_SIG, confidence);
            }
            */
            status_ = Q_TRAN(&ProximityEvtSimulator_running);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::ProximityEvtSimulator} #####################################*/
/*$define${AOs::LineEvtSimulator} ##########################################*/
/*${AOs::LineEvtSimulator} .................................................*/
/*${AOs::LineEvtSimulator::printToLCD} .....................................*/
static void LineEvtSimulator_printToLCD(LineEvtSimulator * const me, uint16_t * lineSensorValues) {
    // On the first line of the LCD, display the bar graph.
    lcd.gotoXY(0, 0);
    for (uint8_t i = 0; i < 5; i++)
    {
        uint8_t barHeight = map(lineSensorValues[i], 0, 2000, 0, 8);
        LineEvtSimulator_printBar(me, barHeight);
    }
}

/*${AOs::LineEvtSimulator::printBar} .......................................*/
static void LineEvtSimulator_printBar(LineEvtSimulator * const me, uint8_t height) {
    if (height > 8) { height = 8; }
    const char barChars[] = {' ', 0, 1, 2, 3, 4, 5, 6, 255};
    lcd.print(barChars[height]);
}

/*${AOs::LineEvtSimulator::SM} .............................................*/
static QState LineEvtSimulator_initial(LineEvtSimulator * const me) {
    /*${AOs::LineEvtSimulator::SM::initial} */
    lineSensors.initFiveSensors();

    QActive_armX(&me->super, 0 /*Tick rate */, me->period /* millis */, me->period);

    // Setup LCD characters required for printing line values to LCD
    static const char levels[] PROGMEM = {
        0, 0, 0, 0, 0, 0, 0, 63, 63, 63, 63, 63, 63, 63
      };
    lcd.loadCustomCharacter(levels + 0, 0);  // 1 bar
    lcd.loadCustomCharacter(levels + 1, 1);  // 2 bars
    lcd.loadCustomCharacter(levels + 2, 2);  // 3 bars
    lcd.loadCustomCharacter(levels + 3, 3);  // 4 bars
    lcd.loadCustomCharacter(levels + 4, 4);  // 5 bars
    lcd.loadCustomCharacter(levels + 5, 5);  // 6 bars
    lcd.loadCustomCharacter(levels + 6, 6);  // 7 bars
    return Q_TRAN(&LineEvtSimulator_running);
}
/*${AOs::LineEvtSimulator::SM::running} ....................................*/
static QState LineEvtSimulator_running(LineEvtSimulator * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::LineEvtSimulator::SM::running::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            unsigned int line_sensor_values[5];
            lineSensors.read(line_sensor_values);

            DO_NOT_PRINT {
                lcd.clear();
                LineEvtSimulator_printToLCD(me, line_sensor_values);
            }

            uint16_t leftSensor   = line_sensor_values[0];
            uint16_t middleSensor = line_sensor_values[2];
            uint16_t rightSensor  = line_sensor_values[4];
            uint16_t threshold    = me->line_sensor_threshold;

            if (leftSensor < threshold && rightSensor < threshold) {    // sensor 0 is on left
              QACTIVE_POST_X((QActive *)&AO_Sumo, 1, ON_BOUNDARY_SIG, me->BOUNDARY_IN_FRONT);
              DO_NOT_PRINT{ lcd.clear(); lcd.print("BOUND_FR");}
            }
            else if (leftSensor < threshold) {    // sensor 0 is on left
              QACTIVE_POST_X((QActive *)&AO_Sumo, 1, ON_BOUNDARY_SIG, me->BOUNDARY_ON_LEFT);
              DO_NOT_PRINT { lcd.clear(); lcd.print("BOUND_L");}
            }
            else if (rightSensor < threshold) {// sensor 4 is on right
              QACTIVE_POST_X((QActive *)&AO_Sumo, 1, ON_BOUNDARY_SIG, me->BOUNDARY_ON_RIGHT);
              DO_NOT_PRINT { lcd.clear(); lcd.print("BOUND_R");}
            }
            //else if (line_sensor_values[2] < me->line_sensor_threshold) { // sensor 2 is on middle.
              //QACTIVE_POST((QActive *)&AO_Sumo, ON_BOUNDARY_SIG, me->BOUNDARY_IN_FRONT);
            //}
            else {
              QACTIVE_POST_X((QActive *)&AO_Sumo, 1, IN_RING_SIG, 0);
              DO_NOT_PRINT { lcd.clear(); lcd.print("INR");}
            }
            status_ = Q_TRAN(&LineEvtSimulator_running);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::LineEvtSimulator} ##########################################*/
//...
